a = float(input("Enter the first number : "))
b = float(input("Enter the second number : "))
print(f'The first number is {a}')
print(f'The second number is {b}')

print(f'Addition is : {a+b}')
print(f'Subtraction is : {a-b}')
print(f'Multiplication is : {a*b}')
print(f'Division is : {a/b}')
print(f'Floor division is : {a//b}')
print(f'Modulus is : {a%b}')